baseURL = 'https://blog.forsh.dev/'
languageCode = 'en-us'
title = "Technical Blog"
theme = 'PaperMod'
googleAnalytics = "G-8GVQ8YS2WJ"

[pagination]
  pagerSize = 5

[params]
  description = "Cloud Security & Infrastructure Architecture"
  author = "Craig Forshaw"
  showShareButtons = true
  showReadingTime = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  
  [params.profileMode]
    enabled = true
    title = "Craig Forshaw"
    subtitle = "Cloud Solutions Architect | Microsoft MVP Cloud Security"
    imageUrl = "https://github.com/craigforshaw.png"
    imageWidth = 150
    imageHeight = 150
    imageTitle = "Craig Forshaw"
    
    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/posts/"
    
    [[params.profileMode.buttons]]
      name = "About"
      url = "/about/"
    
    [[params.profileMode.buttons]]
      name = "Tags"
      url = "/tags/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/craigforshaw"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/craig4shaw"

[[params.socialIcons]]
  name = "Other"
  url = "https://sessionize.com/craig4shaw83"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
